spring:
  application:
    name: order-service

  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: nihar
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

inventory-service:
  base-url: http://localhost:8080/inventory

server:
  port: 9008
